### Recommendations with MovieTweetings: Most Popular Recommendation

Now that you have created the necessary columns we will be using throughout the rest of the lesson on creating recommendations, let's get started with the first of our recommendations.

To get started, read in the libraries and the two datasets you will be using throughout the lesson using the code below.

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tests as t

%matplotlib inline

# Read in the datasets
movies = pd.read_csv('movies_clean.csv')
reviews = pd.read_csv('reviews_clean.csv')
del movies['Unnamed: 0']
del reviews['Unnamed: 0']

In [19]:
reviews.head()

,user_id,movie_id,rating,timestamp,date,month_1,month_2,month_3,month_4,month_5,...,month_9,month_10,month_11,month_12,year_2013,year_2014,year_2015,year_2016,year_2017,year_2018
0,1,68646,10,1381620027,2013-10-12 23:20:27,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
1,1,113277,10,1379466669,2013-09-18 01:11:09,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,2,422720,8,1412178746,2014-10-01 15:52:26,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
3,2,454876,8,1394818630,2014-03-14 17:37:10,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,2,790636,7,1389963947,2014-01-17 13:05:47,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

#### Part I: How To Find The Most Popular Movies?

For this notebook, we have a single task.  The task is that no matter the user, we need to provide a list of the recommendations based on simply the most popular items.

For this task, we will consider what is "most popular" based on the following criteria:

* A movie with the highest average rating is considered best
* With ties, movies that have more ratings are better
* A movie must have a minimum of 5 ratings to be considered among the best movies
* If movies are tied in their average rating and number of ratings, the ranking is determined by the movie that is the most recent rating

With these criteria, the goal for this notebook is to take a **user_id** and provide back the **n_top** recommendations.  Use the function below as the scaffolding that will be used for all the future recommendations as well.

In [20]:
movie_ratings = reviews.groupby('movie_id')['rating']
avg_ratings = movie_ratings.mean()

In [21]:
rating_count_df = pd.DataFrame({'avg_rating': avg_ratings, 'num_ratings': num_ratings})
rating_count_df = rating_count_df.join(last_rating)

# merge with the movies dataset
movie_recs = movies.set_index('movie_id').join(rating_count_df)

In [22]:
def create_ranked_df(movies, reviews):
        '''
        INPUT
        movies - the movies dataframe
        reviews - the reviews dataframe
        
        OUTPUT
        ranked_movies - a dataframe with movies that are sorted by highest avg rating, more reviews, 
                        then time, and must have more than 4 ratings
        '''
        
        # Pull the average ratings and number of ratings for each movie
        movie_ratings = reviews.groupby('movie_id')['rating']
        avg_ratings = movie_ratings.mean()
        num_ratings = movie_ratings.count()
        last_rating = pd.DataFrame(reviews.groupby('movie_id').max()['date'])
        last_rating.columns = ['last_rating']

        # Add Dates
        rating_count_df = pd.DataFrame({'avg_rating': avg_ratings, 'num_ratings': num_ratings})
        rating_count_df = rating_count_df.join(last_rating)

        # merge with the movies dataset
        movie_recs = movies.set_index('movie_id').join(rating_count_df)

        # sort by top avg rating and number of ratings
        ranked_movies = movie_recs.sort_values(['avg_rating', 'num_ratings', 'last_rating'], ascending=False)

        # for edge cases - subset the movie list to those with only 5 or more reviews
        ranked_movies = ranked_movies[ranked_movies['num_ratings'] > 4]
        
        return ranked_movies
    

def popular_recommendations(user_id, n_top, ranked_movies):
    '''
    INPUT:
    user_id - the user_id (str) of the individual you are making recommendations for
    n_top - an integer of the number recommendations you want back
    ranked_movies - a pandas dataframe of the already ranked movies based on avg rating, count, and time

    OUTPUT:
    top_movies - a list of the n_top recommended movies by movie title in order best to worst
    '''

    top_movies = list(ranked_movies['movie'][:n_top])

    return top_movies

Usint the three criteria above, you should be able to put together the above function.  If you feel confident in your solution, check the results of your function against our solution. On the next page, you can see a walkthrough and you can of course get the solution by looking at the solution notebook available in this workspace.

In [26]:
# Top 20 movies recommended for id 1
ranked_movies = create_ranked_df(movies, reviews) # only run this once - it is not fast

recs_20_for_1 = popular_recommendations('1', 20, ranked_movies)

# Top 5 movies recommended for id 53968
recs_5_for_53968 = popular_recommendations('53968', 5, ranked_movies)

# Top 100 movies recommended for id 70000
recs_100_for_70000 = popular_recommendations('70000', 100, ranked_movies)

# Top 35 movies recommended for id 43
recs_35_for_43 = popular_recommendations('43', 35, ranked_movies)

recs_35_for_43

['MSG 2 the Messenger (2015)',
 'Avengers: Age of Ultron Parody (2015)',
 'Sorry to Bother You (2018)',
 'Selam (2013)',
 "Quiet Riot: Well Now You're Here, There's No Way Back (2014)",
 'Crawl Bitch Crawl (2012)',
 'Make Like a Dog (2015)',
 'Pandorica (2016)',
 'Third Contact (2011)',
 'Romeo Juliet (2009)',
 'Be Somebody (2016)',
 'Birlesen Gonuller (2014)',
 'Agnelli (2017)',
 'SÃ¡tÃ¡ntangÃ³ (1994)',
 'Shijie (2004)',
 'Foster (2011)',
 'CM101MMXI Fundamentals (2013)',
 'Akahige (1965)',
 'Crystal Lake Memories: The Complete History of Friday the 13th (2013)',
 'KÃ¶rkarlen (1921)',
 'Tengoku to jigoku (1963)',
 'Kirik Party (2016)',
 'Chasing Asylum (2016)',
 'Beyond the Sea (2004)',
 'Blood Brother (2013)',
 'Poshter Girl (2016)',
 'The Adventures of Robin Hood (1938)',
 'Umberto D. (1952)',
 'Bridegroom (2013)',
 'No Stone Unturned (2017)',
 'Mad As Hell (2014)',
 'Nashville (1975)',
 'The Shawshank Redemption (1994)',
 'A Matter of Life and Death (1946)',
 'Cyborgs: Heroes Never Die (2017)']

**Notice:** This wasn't the only way we could have determined the "top rated" movies.  You can imagine that in keeping track of trending news or trending social events, you would likely want to create a time window from the current time, and then pull the articles in the most recent time frame.  There are always going to be some subjective decisions to be made.  

If you find that no one is paying any attention to your most popular recommendations, then it might be time to find a new way to recommend, which is what the next parts of the lesson should prepare us to do!

### Part II: Adding Filters

Now that you have created a function to give back the **n_top** movies, let's make it a bit more robust.  Add arguments that will act as filters for the movie **year** and **genre**.  

Use the cells below to adjust your existing function to allow for **year** and **genre** arguments as **lists** of **strings**.  Then your ending results are filtered to only movies within the lists of provided years and genres (as `or` conditions).  If no list is provided, there should be no filter applied.

You can adjust other necessary inputs as necessary to retrieve the final results you are looking for!

In [24]:
def popular_recs_filtered(user_id, n_top, ranked_movies, years=None, genres=None):
    '''
    REDO THIS DOC STRING
    
    INPUT:
    user_id - the user_id (str) of the individual you are making recommendations for
    n_top - an integer of the number recommendations you want back
    ranked_movies - a pandas dataframe of the already ranked movies based on avg rating, count, and time
    years - a list of strings with years of movies
    genres - a list of strings with genres of movies
    
    OUTPUT:
    top_movies - a list of the n_top recommended movies by movie title in order best to worst
    '''
    # Filter movies based on year and genre
    if years is not None:
        ranked_movies = ranked_movies[ranked_movies['date'].isin(years)]

    if genres is not None:
        num_genre_match = ranked_movies[genres].sum(axis=1)
        ranked_movies = ranked_movies.loc[num_genre_match > 0, :]
            
            
    # create top movies list 
    top_movies = list(ranked_movies['movie'][:n_top])

    return top_movies

In [25]:
# Top 20 movies recommended for id 1 with years=['2015', '2016', '2017', '2018'], genres=['History']
recs_20_for_1_filtered = popular_recs_filtered('1', 20, ranked_movies, years=['2015', '2016', '2017', '2018'], genres=['History'])

# Top 5 movies recommended for id 53968 with no genre filter but years=['2015', '2016', '2017', '2018']
recs_5_for_53968_filtered = popular_recs_filtered('53968', 5, ranked_movies, years=['2015', '2016', '2017', '2018'])

# Top 100 movies recommended for id 70000 with no year filter but genres=['History', 'News']
recs_100_for_70000_filtered = popular_recs_filtered('70000', 100, ranked_movies, genres=['History', 'News'])

recs_100_for_70000_filtered

['Birlesen Gonuller (2014)',
 'Seppuku (1962)',
 "La passion de Jeanne d'Arc (1928)",
 'Ayla: The Daughter of War (2017)',
 'The Decline of Western Civilization (1981)',
 'Night Will Fall (2014)',
 'I Believe in Miracles (2015)',
 "Schindler's List (1993)",
 'Judgment at Nuremberg (1961)',
 'The Culture High (2014)',
 'Let the Fire Burn (2013)',
 'For Greater Glory: The True Story of Cristiada (2012)',
 'Braveheart (1995)',
 'In the Name of the Father (1993)',
 'Requiem for the American Dream (2015)',
 'Andrey Rublyov (1966)',
 'The Farthest (2017)',
 'The Mask You Live In (2015)',
 'Mrs Brown (1997)',
 'Nanjing! Nanjing! (2009)',
 'Aguirre, der Zorn Gottes (1972)',
 'Alive Inside (2014)',
 'A Bridge Too Far (1977)',
 'Russkiy kovcheg (2002)',
 'Pearl Jam Twenty (2011)',
 'Gandhi (1982)',
 'JFK (1991)',
 'Sado (2015)',
 'Mai wei (2011)',
 'Inherit the Wind (1960)',
 'In Cold Blood (1967)',
 'Hatred (2016)',
 'The Long Walk Home (1990)',
 'Ugetsu monogatari (1953)',
 'Il gattopardo (1963)',
 'Trilogia: To livadi pou dakryzei (2004)',
 'The Devils (1971)',
 'Hotel Rwanda (2004)',
 'The Right Stuff (1983)',
 'Nuit et brouillard (1955)',
 'Deep Water (2006)',
 'Al Midan (2013)',
 'Seabiscuit (2003)',
 "The King's Speech (2010)",
 'Talk to Me (2007)',
 'Marina Abramovic: The Artist Is Present (2012)',
 '12 Years a Slave (2013)',
 'In the Shadow of the Moon (2007)',
 'Kincsem (2017)',
 'How to Survive a Plague (2012)',
 'The Alamo (2004)',
 'Choi-jong-byeong-gi Hwal (2011)',
 'Red Army (2014)',
 'Jeder fÃ¼r sich und Gott gegen alle (1974)',
 'Gallipoli (1981)',
 "Jodorowsky's Dune (2013)",
 'Tombstone (1993)',
 'Rang De Basanti (2006)',
 'Nise - O CoraÃ§Ã£o da Loucura (2015)',
 'LA 92 (2017)',
 'The Great Escape (1963)',
 'Citizenfour (2014)',
 'Straight Outta Compton (2015)',
 'The Last Samurai (2003)',
 'Manjhi: The Mountain Man (2015)',
 'The Fog of War: Eleven Lessons from the Life of Robert S. McNamara (2003)',
 'Ying xiong (2002)',
 "Tim's Vermeer (2013)",
 'The Killing Fields (1984)',
 'The Act of Killing (2012)',
 'The Wind That Shakes the Barley (2006)',
 'Lion of the Desert (1981)',
 'Battle of Britain (1969)',
 'Zulu (1964)',
 'The Last Emperor (1987)',
 'Letters from Iwo Jima (2006)',
 'The Barkley Marathons: The Race That Eats Its Young (2014)',
 'Glory (1989)',
 'A Man for All Seasons (1966)',
 'Kagemusha (1980)',
 'Gwanghae, Wangyidoen namja (2012)',
 'Chi bi xia: Jue zhan tian xia (2009)',
 'Frost/Nixon (2008)',
 'A Night to Remember (1958)',
 'The Corporation (2003)',
 'Only the Dead (2015)',
 'Nanking (2007)',
 'The Revisionaries (2012)',
 'The Dam Busters (1955)',
 'Spotlight (2015)',
 'Under sandet (2015)',
 "All the President's Men (1976)",
 'A Passage to India (1984)',
 'Il vangelo secondo Matteo (1964)',
 '1 (2013)',
 'Les MisÃ©rables (1998)',
 'The Search for General Tso (2014)',
 'Missing (1982)',
 'Last Days in Vietnam (2014)',
 'Elizabeth (1998)']